/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: Juan Martinez Sanjurjo (https://sketchfab.com/JuanSanjurjo)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/advanced-game-characters-week-2-jacket-8f211f057bb24f5db17ca659553b716b
title: Advanced Game Characters - Week 2 Jacket
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTFLoader, DRACOLoader } from 'three-stdlib'

export default function Model(props) {
  const group = useRef()
  const loader = new GLTFLoader();
  const dracoLoader = new DRACOLoader();
  dracoLoader.setDecoderPath( '/draco/gltf/' );
  loader.setDRACOLoader( dracoLoader );

  const {nodes, materials} = useGLTF(`../${props.permalink}/scene.gltf`)

  console.log(props.permalink);

  
  

  return (
    <group ref={group} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.defaultMaterial.geometry} material={materials.Jacket_Lv2_Jacket} material-color={props.color}/>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/scene.gltf')
